#! /bin/bash

echo
echo "Make the book"
echo "-------------"
cd src
gcc mk_book.c -o mk_book
./mk_book openings.txt
rm mk_book
cd ..

echo
echo "Compile the SDL2 standalone game"
echo "--------------------------------"
# For gdb replace -s option (strip) by -g (gdb)
gcc src/chess.c src/engine.c -o chess -Wall -Wextra -Wimplicit-fallthrough=0 -Wpedantic `sdl2-config --libs` -lpthread -lSDL2_image -lSDL2_ttf -O3 -DWITH_BOOK -s

echo
echo "Archive all the files needed to run it"
echo "--------------------------------------"
tar -czvf chess.tar.gz chess resources

echo
echo "Compile for XBOARD"
echo "------------------"
# For gdb replace -s option (strip) by -g (gdb)
gcc src/chessx.c src/engine.c -o chessx -Wall -Wextra -Wimplicit-fallthrough=0 -Wpedantic -lpthread -O3 -DWITH_BOOK -s
echo

